### ISSUE TITLE
Periodic tasks fail due to "cannot translate host name" error

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#222]
```
[2019-01-03 00:25:41,820] {models.py:1736} ERROR - (psycopg2.OperationalError) could not translate host name "geodetic-gyroscope-0611-pgbouncer" to address: Try again
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 768, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1231, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "geodetic-gyroscope-0611-pgbouncer" to address: Try again
```

Jobs will periodically fail with this error - not much consistency or anything to it.  We've only seen it with the Clickstream loader.

**Comment by ryw** [comment]
@andrewhharmon do we still see this error?

**Comment by andrewhharmon** [comment]
I have not noticed that since I started. Id need to check if that deployment is pushing failures to slack like the other deployments. If so, then I’ve definitely never seen that error
