### ISSUE TITLE
500 when a user tries to sign up with Oauth when public signups are disabled

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/astronomer#410]
**Describe the bug**

When a user tries to sign up when public signups are disabled, they encounter a 500.

**To Reproduce**

@petedejoy please provide steps to reproduce

**Expected behavior**

informative error message like "please ask for an invite"

**Additional context**
```
2019-08-08T15:01:42 DEBUG ::ffff:10.32.0.77 - OPTIONS /v1 HTTP/1.1 204 0 - 0.176 ms
2019-08-08T15:01:42 DEBUG ::ffff:10.32.0.77 - POST /v1 HTTP/1.1 200 1483 - 22.489 ms
2019-08-08T15:01:47 DEBUG ::ffff:10.32.0.77 - POST /v1/oauth/callback HTTP/1.1 500 148 - 383.190 ms
InviteTokenEmailError: This email is not associated with the specified invite token
    at Object.validateInviteToken (/houston/dist/lib/users/index.js:175:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ryw** [comment]
Email capitalization def wasn’t the issue here, right? That was my prob for earlier this week

**Comment by petedejoy** [comment]
Yup- confirmed it was caused by trying to login with an email address that hadn't been "invited" to a private signup cluster yet.

**Comment by petedejoy** [comment]
Had a few more customers run into this over the weekend- would love to get this bumped up the queue if possible @ryw!

**Comment by ryw** [comment]
As soon as we ship v0.10 we'll look at this
