### ISSUE TITLE
ValueError: Unable to configure handler 'processor': Permission denied: '/usr/local/airflow/logs/scheduler/

### ISSUE THREAD

**Issue by lapidus** [astronomer/astronomer#500]
**Describe the bug**

Problem with permissions on Debian image:
`FROM astronomerio/ap-airflow:debian-alpha.1-onbuild
`

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 44, in <module>
    settings.initialize()
  File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 287, in initialize
    LOGGING_CLASS_PATH = configure_logging()
  File "/usr/local/lib/python3.6/site-packages/airflow/logging_config.py", line 68, in configure_logging
    raise e
  File "/usr/local/lib/python3.6/site-packages/airflow/logging_config.py", line 63, in configure_logging
    dictConfig(logging_config)
  File "/usr/local/lib/python3.6/logging/config.py", line 802, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.6/logging/config.py", line 573, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'processor': [Errno 13] Permission denied: '/usr/local/airflow/logs/scheduler/2019-10-02'
```

**To Reproduce**

Running astro airflow start leads to webserver "restarting ..."

**Comment by vparekh94** [comment]
Hi @lapidus. If you are a customer, can you please submit this at support@astronomer.io ? That way we can track the request :).

From first look here, this seems like a permissions error on the directories you are building into the image. Some chmod'ing _should- do the trick, but I'll close this issue for now and we can discuss more on the support ticket :smile:
