### ISSUE TITLE
pyspark airflow error

### ISSUE THREAD

**Issue by SallyOsama** [astronomer/astronomer#726]
2020-06-18 05:43:19,479] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): sparkprint> on 2020-05-31T00:12:00+00:00
[2020-06-18 05:43:19,484] {standard_task_runner.py:53} INFO - Started process 13729 to run task
[2020-06-18 05:43:19,576] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: sparkprint.sparkprint 2020-05-31T00:12:00+00:00 [running]> dissed1.fyre.ibm.com
[2020-06-18 05:43:19,676] {taskinstance.py:1145} ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/printspark.py", line 28, in sparkprint
    sc =SparkContext()
  File "/usr/lib/python2.7/site-packages/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/usr/lib/python2.7/site-packages/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/usr/lib/python2.7/site-packages/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/usr/lib/python2.7/site-packages/pyspark/java_gateway.py", line 98, in _launch_gateway
    proc = Popen(command, stdin=PIPE, preexec_fn=preexec_func, env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2020-06-18 05:43:19,679] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=sparkprint, task_id=sparkprint, execution_date=20200531T001200, start_date=20200618T124319, end_date=20200618T124319
[2020-06-18 05:43:29,400] {logging_mixin.py:112} INFO - [2020-06-18 05:43:29,399] {local_task_job.py:103} INFO - Task exited with return code 1

**Comment by paolaperaza** [comment]
Hey @SallyOsama ! I'm doing some cleanup in our GH repos and seeing that this issue is still open. I'm going to go ahead and close this out since it's not the best place to get support from our team, but if you're still experiencing the above we're happy to help.

You can always:
- Post on our [Community Forum](forum.astronomer.io)
- Reach out to our [Support Team](https://support.astronomer.io)

Appreciate you being onboard with us!
